# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VenueList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=255)),
                ('venue_url', models.CharField(max_length=255)),
                ('venue_address', models.CharField(max_length=255)),
                ('venue_lat_long', models.CharField(max_length=255)),
                ('venue_contact', models.TextField(max_length=255)),
                ('venue_details', models.TextField(max_length=255)),
                ('venue_city', models.CharField(max_length=255)),
            ],
        ),
    ]
