# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_id', models.IntegerField(max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('event_price', models.IntegerField(max_length=255)),
                ('event_detail', models.TextField(max_length=255)),
                ('time_start_end', models.CharField(max_length=255)),
                ('event_url', models.CharField(max_length=255)),
                ('event_img_url', models.CharField(max_length=255)),
            ],
        ),
    ]
