# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 12:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170724_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlist',
            name='event_date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
