# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170724_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlist',
            name='event_date_time',
            field=models.DateField(),
        ),
    ]
