# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170724_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlist',
            name='venue_id',
        ),
        migrations.AddField(
            model_name='eventlist',
            name='venue',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.VenueList'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventlist',
            name='event_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
