# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170813_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlist',
            name='time_start_end',
        ),
        migrations.AddField(
            model_name='eventlist',
            name='event_time_end',
            field=models.TimeField(default='16:20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventlist',
            name='event_time_start',
            field=models.TimeField(default='4:20'),
            preserve_default=False,
        ),
    ]
